services:
  nlp:
    build: .
    image: search-model-nlp:latest
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - path: .env
        required: true
    environment:
      - PYTHONPATH=/app
    user: "${UID:-1000}:${GID:-1000}"
